---
services:
  db:
    image: postgres:16-alpine
    container_name: mediamanager-db
    environment:
      - POSTGRES_USER=mediamanager
      - POSTGRES_PASSWORD=mediamanager
      - POSTGRES_DB=mediamanager
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
